quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceNameLower}}_test.go"
outpkg: "{{.PackageName}}"
dir: "{{.InterfaceDir}}"
inpackage: True
packages:
  github.com/mbretter/go-mmcli-svr:
    interfaces:
      smsHandlersInterface:
      locationHandlersInterface:
      modemHandlersInterface:
  github.com/mbretter/go-mmcli-svr/backend:
    config:
      filename: "{{.InterfaceNameLower}}_mock.go"
    interfaces:
      Backend:
  github.com/mbretter/go-mmcli-svr/backend/mmcli:
    interfaces:
      ExecCommand:
      ExecCommandOutput:
