quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceNameLower}}_test.go"
outpkg: "{{.PackageName}}"
dir: "{{.InterfaceDir}}"
inpackage: True
packages:
  go-mmcli-svr/backend:
    config:
      filename: "{{.InterfaceNameLower}}_mock.go"
    interfaces:
      Backend:
  go-mmcli-svr/backend/mmcli:
    interfaces:
      ExecCommand:
      ExecCommandOutput:
