// Code generated by mockery. DO NOT EDIT.

package main

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// locationHandlersInterfaceMock is an autogenerated mock type for the locationHandlersInterface type
type locationHandlersInterfaceMock struct {
	mock.Mock
}

type locationHandlersInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *locationHandlersInterfaceMock) EXPECT() *locationHandlersInterfaceMock_Expecter {
	return &locationHandlersInterfaceMock_Expecter{mock: &_m.Mock}
}

// LocationGet provides a mock function with given fields: w, r
func (_m *locationHandlersInterfaceMock) LocationGet(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// locationHandlersInterfaceMock_LocationGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocationGet'
type locationHandlersInterfaceMock_LocationGet_Call struct {
	*mock.Call
}

// LocationGet is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *locationHandlersInterfaceMock_Expecter) LocationGet(w interface{}, r interface{}) *locationHandlersInterfaceMock_LocationGet_Call {
	return &locationHandlersInterfaceMock_LocationGet_Call{Call: _e.mock.On("LocationGet", w, r)}
}

func (_c *locationHandlersInterfaceMock_LocationGet_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *locationHandlersInterfaceMock_LocationGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *locationHandlersInterfaceMock_LocationGet_Call) Return() *locationHandlersInterfaceMock_LocationGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *locationHandlersInterfaceMock_LocationGet_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *locationHandlersInterfaceMock_LocationGet_Call {
	_c.Call.Return(run)
	return _c
}

// newLocationHandlersInterfaceMock creates a new instance of locationHandlersInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newLocationHandlersInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *locationHandlersInterfaceMock {
	mock := &locationHandlersInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
